'''This file is a part of the work 'Nucleation patterns of polymer crystals analyzed by machine learning models' and is written by Atmika Bhardwaj (bhardwaj@ipfdd.de). 

It reads dump files generated by LAMMPS and calculate the local environmental information of every coarse-grained bead. This information is written in an hdf5 file, AO_P2.h5

This file imports all the functions from another file called all_functions.py. Another file control_parameters.py imports all the tuned parameters.'''

import numpy as np
import h5py as h5py
import sys
from   all_functions import *
import pickle
import glob
from   natsort import natsorted
import control_parameters

param         = control_parameters.get_defaults()
chainLength   = param["chainlength"]
Rmax          = param["Rmax"]
g             = natsorted(glob.glob('../../01_raw_data/dump_files/dump.*'))
file          = h5py.File('../../02_processed_data/Labels/AO_P2.h5', 'w')

num = 1
for i in g:
    obj  = ReadCoordinates(i, chainLength)
    rnd  = np.arange(obj.totalAtoms)
    print('Total atoms = ', obj.totalAtoms)
    print(num)
    grid = GridSearch(obj, numSigma = 6.0)
    grid.updateNeighborLists(obj, rnd, Rmax)
    print ("num per cell = ",grid.numPerCell)
    av   = avgor(grid, obj)
    file.create_dataset(name = str(num), data = av, compression="gzip")
    num += 1
file.close()
